#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# the "app_lucky_number" route name is not important yet
# accueil

page:
    path: /page
    controller: App\Controller\PageController::index
login:
    path: /login
    controller: App\Controller\LoginController::index
register: 
    path: /register
    controller: App\Controller\RegisterController::index
admin:
    path: /admin
    controller : App\Controller\AdminController::index
add:
    path: /add
    controller : App\Controller\addController::index
update:
    path: update
    controller : App\Controller\updateController::index
delete:
    path:delete
    controller : App\Controller\delete\Controller::index
see: 
    path: /see
    controller : App\Controller\seeController::index
select:
    path: /select
    controller: App\Controller\selectController::index
reserve:
    path: /reserve
    controller: App\Controller\reserve'Controller::index