#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
page:
    path: /page
    controller: App\Controller\PageController::index
login:
    path: /login
    controller: App\Controller\LoginController::index
register: 
    path: /register
    controller: App\Controller\RegisterController::index