<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcRKhXt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcRKhXt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIcRKhXt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIcRKhXt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIcRKhXt\App_KernelDevDebugContainer([
    'container.build_hash' => 'IcRKhXt',
    'container.build_id' => '640990e1',
    'container.build_time' => 1650569098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcRKhXt');
