<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaBSeXY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaBSeXY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXaBSeXY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXaBSeXY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXaBSeXY\App_KernelDevDebugContainer([
    'container.build_hash' => 'XaBSeXY',
    'container.build_id' => 'ac9e93fc',
    'container.build_time' => 1650527948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaBSeXY');
